### ISSUE TITLE
Missing file problem

### ISSUE THREAD

**Issue by ckj01** [rmaphoh/AutoMorph#12]
Hello, when I run your project, it shows that a file is missing, something like this:
FileNotFoundError: [Errno 2] No such file or directory: './Results/M3/Disc_centred/Disc_Measurement.csv'
Could you tell me where the problem is? Thank you very much!

**Comment by TanXi789** [comment]
Have you resolved this issue?

**Comment by lajos-cs** [comment]
Hi Have the same issue. Even when try to run the code on the test image stets. See full report below. 



%%shell
cd AutoMorph
eval "$(conda shell.bash hook)" # copy conda command to shell
source activate automorph
#python generate_resolution.py
sh run.sh



Mon Mar 24 10:57:59 AM UTC 2025
AUTOMORPH_DATA not set, using default directory
### Preprocess Start ###
### Image Quality Assessment ###
INFO: Neither CUDA nor MPS is available. Using CPU...
INFO: Using device cpu
Downloading: "https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/efficientnet-b4-6ed6700e.pth" to /root/.cache/torch/hub/checkpoints/efficientnet-b4-6ed6700e.pth
100% 74.4M/74.4M [00:00<00:00, 211MB/s]
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
Loaded pretrained weights for efficientnet-b4
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:243: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_1, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:246: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_2, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:249: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_3, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:252: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_4, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:255: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_5, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:258: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_6, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:261: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_7, map_location=device)
/content/AutoMorph/M1_Retinal_Image_quality_EyePACS/test_outside.py:264: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(checkpoint_path_8, map_location=device)
INFO: Creating dataset with 3 examples
/usr/local/envs/automorph/lib/python3.11/site-packages/torch/utils/data/dataloader.py:617: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
Epoch 1/1: 100% 3/3 [00:37<00:00, 12.48s/img]
Gradable cases by EyePACS_QA is 2 
Ungradable cases by EyePACS_QA is 1 
### Segmentation Modules ###
Mon Mar 24 10:58:56 AM UTC 2025
Traceback (most recent call last):
  File "/content/AutoMorph/M2_Vessel_seg/test_outside_integrated.py", line 15, in <module>
    from skimage.morphology import skeletonize,remove_small_objects
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/__init__.py", line 9, in <module>
    from .binary import binary_closing, binary_dilation, binary_erosion, binary_opening
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/binary.py", line 9, in <module>
    from .misc import default_footprint
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/misc.py", line 9, in <module>
    from .._shared._dependency_checks import is_wasm
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/_dependency_checks.py", line 5, in <module>
    has_mpl = is_installed("matplotlib", ">=3.3")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/version_requirements.py", line 58, in is_installed
    actver = get_module_version(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/version_requirements.py", line 32, in get_module_version
    mod = __import__(module_name, fromlist=[module_name.rpartition('.')[-1]])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Mon Mar 24 10:59:01 AM UTC 2025
Mon Mar 24 10:59:01 AM UTC 2025
Traceback (most recent call last):
  File "/content/AutoMorph/M2_Artery_vein/test_outside.py", line 21, in <module>
    from skimage.morphology import skeletonize,remove_small_objects
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/__init__.py", line 9, in <module>
    from .binary import binary_closing, binary_dilation, binary_erosion, binary_opening
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/binary.py", line 9, in <module>
    from .misc import default_footprint
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/misc.py", line 9, in <module>
    from .._shared._dependency_checks import is_wasm
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/_dependency_checks.py", line 5, in <module>
    has_mpl = is_installed("matplotlib", ">=3.3")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/version_requirements.py", line 58, in is_installed
    actver = get_module_version(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/version_requirements.py", line 32, in get_module_version
    mod = __import__(module_name, fromlist=[module_name.rpartition('.')[-1]])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Mon Mar 24 10:59:06 AM UTC 2025
Mon Mar 24 10:59:06 AM UTC 2025
Traceback (most recent call last):
  File "/content/AutoMorph/M2_lwnet_disc_cup/generate_av_results.py", line 18, in <module>
    from skimage.morphology import remove_small_objects
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/__init__.py", line 9, in <module>
    from .binary import binary_closing, binary_dilation, binary_erosion, binary_opening
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/binary.py", line 9, in <module>
    from .misc import default_footprint
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/morphology/misc.py", line 9, in <module>
    from .._shared._dependency_checks import is_wasm
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/_dependency_checks.py", line 5, in <module>
    has_mpl = is_installed("matplotlib", ">=3.3")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/version_requirements.py", line 58, in is_installed
    actver = get_module_version(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/skimage/_shared/version_requirements.py", line 32, in get_module_version
    mod = __import__(module_name, fromlist=[module_name.rpartition('.')[-1]])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Mon Mar 24 10:59:13 AM UTC 2025
### Feature measuring ###
Traceback (most recent call last):
  File "/content/AutoMorph/M3_feature_zone/retipy/create_datasets_disc_centred_B.py", line 34, in <module>
    from retipy import configuration, retina, tortuosity_measures
  File "/content/AutoMorph/M3_feature_zone/retipy/retipy/retina.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/content/AutoMorph/M3_feature_zone/retipy/create_datasets_disc_centred_C.py", line 34, in <module>
    from retipy import configuration, retina, tortuosity_measures
  File "/content/AutoMorph/M3_feature_zone/retipy/retipy/retina.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/content/AutoMorph/M3_feature_zone/retipy/create_datasets_macular_centred_B.py", line 34, in <module>
    from retipy import configuration, retina, tortuosity_measures
  File "/content/AutoMorph/M3_feature_zone/retipy/retipy/retina.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/content/AutoMorph/M3_feature_zone/retipy/create_datasets_macular_centred_C.py", line 34, in <module>
    from retipy import configuration, retina, tortuosity_measures
  File "/content/AutoMorph/M3_feature_zone/retipy/retipy/retina.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/content/AutoMorph/M3_feature_whole_pic/retipy/create_datasets_macular_centred.py", line 34, in <module>
    from retipy import configuration, retina, tortuosity_measures
  File "/content/AutoMorph/M3_feature_whole_pic/retipy/retipy/retina.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/content/AutoMorph/M3_feature_whole_pic/retipy/create_datasets_disc_centred.py", line 34, in <module>
    from retipy import configuration, retina, tortuosity_measures
  File "/content/AutoMorph/M3_feature_whole_pic/retipy/retipy/retina.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 1270, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
    ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/matplotlib/__init__.py", line 738, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
Traceback (most recent call last):
  File "/content/AutoMorph/csv_merge.py", line 8, in <module>
    Disc_whole_image = pd.read_csv(f'{AUTOMORPH_DATA}/Results/M3/Disc_centred/Disc_Measurement.csv')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1024, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 618, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1618, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1878, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/usr/local/envs/automorph/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './Results/M3/Disc_centred/Disc_Measurement.csv'
### Done ###
Mon Mar 24 10:59:18 AM UTC 2025

**Comment by lajos-cs** [comment]
Amazing! Thanks for fixing it! :)
lajos
